# Generated by Django 4.1 on 2023-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_item_image2_alter_item_image3"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilePhone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="phone_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="street_address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
