# Generated by Django 4.1 on 2023-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_mobilephone_billingaddress_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image2",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="billingaddress",
            name="zip",
            field=models.CharField(max_length=5),
        ),
    ]
