# Generated by Django 4.2 on 2023-05-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_image2_alter_billingaddress_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image2',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip',
            field=models.IntegerField(max_length=5),
        ),
    ]
