# Generated by Django 4.2 on 2023-05-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_billingaddress_apartment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reciept',
            field=models.ImageField(null=True, upload_to='reciepts'),
        ),
    ]
