# Generated by Django 4.2 on 2023-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
