# Generated by Django 4.2 on 2023-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(choices=[('iPhone 11', 'iPhone 11'), ('iPhone 11 pro', 'iPhone 11 pro')], max_length=50, null=True),
        ),
    ]
