# Generated by Django 4.2 on 2023-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
