# Generated by Django 4.2 on 2023-05-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
